"""add RBAC role and patient profile fields

Revision ID: 000a04a40253
Revises: c2c0d0e9327c
Create Date: 2026-09-21 02:29:43.415823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000a04a40253'
down_revision: Union[str, None] = 'c2c0d0e9327c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required here: existing rows in a populated `users`
    # table need a value for this new NOT NULL column. The Python-side
    # default on the model (default="patient") only applies to new rows
    # inserted through the ORM, not to rows that already exist.
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='patient'))
    op.add_column('users', sa.Column('patient_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.add_column('users', sa.Column('medical_details', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_patient_code'), 'users', ['patient_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_patient_code'), table_name='users')
    op.drop_column('users', 'medical_details')
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'address')
    op.drop_column('users', 'age')
    op.drop_column('users', 'patient_code')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
