"""add normalizer fields: device vendor/battery/sync, vendor_credentials table

Revision ID: 341d330d1b92
Revises: 000a04a40253
Create Date: 2026-09-28 22:32:13.705507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types


# revision identifiers, used by Alembic.
revision: str = '341d330d1b92'
down_revision: Union[str, None] = '000a04a40253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_credentials',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('device_id', app.types.GUID(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_credentials_device_id'), 'vendor_credentials', ['device_id'], unique=True)
    op.add_column('devices', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('vendor_device_id', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('battery_level', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_synced_at')
    op.drop_column('devices', 'battery_level')
    op.drop_column('devices', 'vendor_device_id')
    op.drop_column('devices', 'vendor')
    op.drop_index(op.f('ix_vendor_credentials_device_id'), table_name='vendor_credentials')
    op.drop_table('vendor_credentials')
    # ### end Alembic commands ###
