"""baseline schema

Revision ID: c2c0d0e9327c
Revises: 
Create Date: 2026-09-09 10:19:20.053782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types


# revision identifiers, used by Alembic.
revision: str = 'c2c0d0e9327c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alert_rules',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('minimum_value', sa.Float(), nullable=True),
    sa.Column('maximum_value', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('ble_identifier', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_owner_id'), 'devices', ['owner_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('device_sessions',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('device_id', app.types.GUID(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.Column('disconnect_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_sessions_device_id'), 'device_sessions', ['device_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('device_id', app.types.GUID(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('quality_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_device_time', 'sensor_readings', ['device_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sensor_readings_device_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_device_sessions_device_id'), table_name='device_sessions')
    op.drop_table('device_sessions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_devices_owner_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
